apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-front-web
  namespace: front-web
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-web
            port:
              number: 80